<?php $helper = Mage::helper('checkout2'); ?>

<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <a title="Payson internetbetalningar" href="https://www.payson.se/" target="_blank"><img src="https://www.payson.se/sites/all/files/images/external/payson150x55_n.png" alt="Payson logo"></img></a>
    <br>
    <p><?php echo $helper->__("The payment is completed on site through Payson's web form") ?></p>
</div
